-- Skill Graph Oracle setup script
-- Run this in SQL Plus while connected as the SAME USER configured in db.properties.
-- Example:
-- sqlplus system/dumbo@localhost:1521/XE
-- @C:\Users\dmadh\SkillGraph\oracle_schema.sql

CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(64) NOT NULL,
    college VARCHAR2(150) NOT NULL,
    branch VARCHAR2(100) NOT NULL,
    graduation_year NUMBER(4) NOT NULL
);

CREATE TABLE SKILLS (
    skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(80) NOT NULL
);

CREATE TABLE USER_SKILLS (
    user_skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    skill_id NUMBER NOT NULL,
    status VARCHAR2(30) DEFAULT 'Pending',
    proficiency_level VARCHAR2(30) DEFAULT 'Beginner',
    CONSTRAINT fk_user_skills_user FOREIGN KEY (user_id) REFERENCES USERS(user_id),
    CONSTRAINT fk_user_skills_skill FOREIGN KEY (skill_id) REFERENCES SKILLS(skill_id)
);

CREATE TABLE RESUMES (
    resume_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    file_path VARCHAR2(500) NOT NULL,
    resume_score NUMBER(3) DEFAULT 0,
    upload_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

CREATE TABLE AI_ROADMAP (
    roadmap_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    target_role VARCHAR2(120) NOT NULL,
    generated_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_roadmap_user FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

CREATE TABLE TASKS (
    task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id NUMBER NOT NULL,
    task_title VARCHAR2(250) NOT NULL,
    status VARCHAR2(30) DEFAULT 'Pending',
    CONSTRAINT fk_tasks_roadmap FOREIGN KEY (roadmap_id) REFERENCES AI_ROADMAP(roadmap_id)
);

CREATE TABLE MOCK_TESTS (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name VARCHAR2(150) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    total_marks NUMBER(5) NOT NULL
);

CREATE TABLE TEST_RESULTS (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    test_id NUMBER NOT NULL,
    score NUMBER(5) NOT NULL,
    date_taken DATE DEFAULT SYSDATE,
    CONSTRAINT fk_results_user FOREIGN KEY (user_id) REFERENCES USERS(user_id),
    CONSTRAINT fk_results_test FOREIGN KEY (test_id) REFERENCES MOCK_TESTS(test_id)
);

CREATE TABLE CHAT_HISTORY (
    chat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    response VARCHAR2(2000) NOT NULL,
    chat_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

CREATE TABLE PROGRESS (
    progress_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    placement_score NUMBER(3) DEFAULT 0,
    last_updated TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

INSERT INTO MOCK_TESTS(test_name, category, total_marks) VALUES ('Aptitude Foundation Test', 'Aptitude', 100);
INSERT INTO MOCK_TESTS(test_name, category, total_marks) VALUES ('Java Basics Test', 'Programming', 100);
INSERT INTO MOCK_TESTS(test_name, category, total_marks) VALUES ('DBMS Core Test', 'Database', 100);

COMMIT;
